apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devapp
data:
  DB_HOST: "mysql-service"
  DB_USER: "user"
  DB_NAME: "appdb"
  PORT: "5000"
  HOST_MODE: "kubernetes"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: devapp
type: Opaque
stringData:
  DB_PASSWORD: "userpass"
  ROOT_PASSWORD: "root"
