---
name: Super-Linter

on: push

permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make scripts executable
        run: chmod +x backend/wait-for-db.sh

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: true
          VALIDATE_MARKDOWN: false
          VALIDATE_HTML: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_YAML: false
          VALIDATE_ENV: false
          VALIDATE_BASH: false
          JSCPD_THRESHOLD: 20
